# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aerragha <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/04 16:38:02 by aerragha          #+#    #+#              #
#    Updated: 2018/10/04 17:52:55 by aerragha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file

SRCS = srcs/*.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean re
